#
# # raise Exception("naujas erroras")
#
# try:
#     my_l = ["pirmas"]
#     print("exceptaas veikia")
#     print(my_l[1])
# except:
#     print("kitkas")

def random_exception():
    print('kazkas')



random_exception()